services:
  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - "3306:3306"
    command: --ssl=0
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build: ./
    container_name: flask_api
    restart: always
    depends_on:
      - db
    env_file: .env
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: mysql+pymysql://$MYSQL_USER:$MYSQL_PASSWORD@db/$MYSQL_DATABASE

volumes:
  mysql_data:
